### ISSUE TITLE
为什么小程序刷新课表后自己添加的自定义课表数据会消失？

### ISSUE THREAD

**Issue by Makonike** [gdutday/gdutday-issue#3]
如题，比如我添加了几个课程的课表数据，但是使用一段时间后，小程序需要重新登陆，登陆后我设置的自定义课表数据消失了。

**Comment by Cerbur** [comment]
这种情况一般是缓存被清理了。为了数据隐私数据都存在了本地端。一些系统的清理工具会清除掉微信小程序的缓存数据。
